# Generated by Django 4.2.4 on 2024-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('board_games', models.FloatField(default=0, verbose_name='Отношение к настольным играм')),
                ('arts', models.FloatField(default=0, verbose_name='Отношение к исскуству')),
                ('sport', models.FloatField(default=0, verbose_name='Отношение к спорту')),
                ('nature', models.FloatField(default=0, verbose_name='Отношение к природе')),
                ('food', models.FloatField(default=0, verbose_name='Отношение к еде')),
                ('duration', models.FloatField(default=0, verbose_name='Предпочтительное время мероприятий')),
                ('capacity', models.FloatField(default=0, verbose_name='Предпочтительное кол-во мест')),
            ],
            options={
                'db_table': 'custon_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('playground', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('duration_in_minutes', models.IntegerField(default=60)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
    ]
