# Generated by Django 4.2.4 on 2024-10-26 13:51

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('playground', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('duration_in_minutes', models.IntegerField(default=60)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=254, verbose_name='Пароль')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('sex', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Пол')),
                ('board_games', models.FloatField(default=0, verbose_name='Отношение к настольным играм')),
                ('arts', models.FloatField(default=0, verbose_name='Отношение к искусству')),
                ('sport', models.FloatField(default=0, verbose_name='Отношение к спорту')),
                ('nature', models.FloatField(default=0, verbose_name='Отношение к природе')),
                ('food', models.FloatField(default=0, verbose_name='Отношение к еде')),
                ('duration', models.FloatField(default=0, verbose_name='Предпочтительное время мероприятий')),
                ('capacity', models.FloatField(default=0, verbose_name='Предпочтительное количество мест')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
                'managed': True,
            },
            managers=[
                ('objects', web.models.CustomUserManager()),
            ],
        ),
    ]
