# Generated by Django 4.2.4 on 2024-10-27 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=254, verbose_name='Пароль')),
                ('sex', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Пол')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('board_games', models.FloatField(default=0, verbose_name='Отношение к настольным играм')),
                ('arts', models.FloatField(default=0, verbose_name='Отношение к искусству')),
                ('sport', models.FloatField(default=0, verbose_name='Отношение к спорту')),
                ('nature', models.FloatField(default=0, verbose_name='Отношение к природе')),
                ('food', models.FloatField(default=0, verbose_name='Отношение к еде')),
                ('duration', models.FloatField(default=0, verbose_name='Предпочтительное время мероприятий')),
                ('capacity', models.FloatField(default=0, verbose_name='Предпочтительное количество мест')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(default='Descr')),
                ('date', models.DateTimeField()),
                ('playground', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('duration_in_minutes', models.IntegerField(default=60)),
                ('capacity', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.category', verbose_name='category')),
                ('creater', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='creater')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_user',
                'managed': True,
                'unique_together': {('event', 'user')},
            },
        ),
    ]
