# Generated by Django 4.2.4 on 2024-10-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=254, verbose_name='Пароль'),
        ),
    ]
